GET {{url}}/user/3

###
POST {{url}}/user
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Sfasdf",
  "username": "alsicv1",
  "email": "aliceasdfasf@example.com",
  "password": "password123"
}
